config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  post "accept_request/:id" => "friendships#accept_request", as: :accept_request
  post "create_friend/:id" => "friendships#create", as: :create_friendship
  get "users/friendrequest/:id" => "users#friendrequest", as: :friendrequest
  get "users/sentrequest/:id" => "users#sentrequest", as: :sentrequest
  get "users/friends/:id" => "users#friends", as: :friends

  resources :friendships, only: [:create, :destroy]

  root :to => "sessions#new"

  resource :session, only: [:new,:create,:destroy]

  get "signin" => "sessions#new"
  get "signup" => "users#new"
  get "signout" => "sessions#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  enum status: {accept: "accept", pending: "pending"}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user


  def all_friends
    self.friends.where("status = 'accept'")+self.inverse_friends.where("status = 'accept'")
  end
  def sent_request
    self.friends.where("status = 'pending'")
  end
  def received_request
    self.inverse_friends.where("status = 'pending'")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :friendship
  def index
    @friendships = current_user.all_friends
  end

  def create
    @friendship = current_user.friendships.new(:friend_id => params[:id])
    if @friendship.save
      flash[:notice] = "Sent Friend Request"
      redirect_to users_path
    end
  end

  def destroy
    @friendship.destroy
    flash[:error] = "Removed Friend"
    redirect_to users_path
  end

  def accept_request
    @friendship.status = "accept"
    @friendship.save
    flash[:notice] = "Accept Request"
    redirect_to users_path
  end

  private
    def friendship
      @friendship = Friendship.find_by(user_id: current_user.id, friend_id: params[:id].to_i)|| Friendship.find_by(friend_id:current_user.id, user_id: params[:id].to_i)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

before_action :required_signin, only: [:destroy]
before_action :required_signout, only: [:new, :create]

  
 def new
 end

 def create
   @email = params[:email]
   @password = params[:password]
   @user = User.find_by(email:@email)

   if @user && @user.authenticate(@password)
    session[:user_id] = @user.id
    flash[:notice] = "#{@user.name} Successfully Signed In"
    redirect_to users_path
   else
     flash.now[:error] = "invalid email/password"
     render :new
   end

 end

 def destroy
  session[:user_id] = nil
  flash[:notice] = "Successfully Signed Out"
  redirect_to signin_path
 end

 private
  def required_signin
    unless current_user
      flash[:error] = "Please Sign In Properly"
      redirect_to signin_path
    end
  end

  def required_signout
    if current_user
      flash[:error] = "Please Sign out Properly"
      redirect_to users_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, except: [:index, :new, :create]
  before_action :required_signin, except: [:index, :create, :new]
  before_action :required_signout, only: [:new, :create]
  before_action :sent, only: [:index, :show, :sentrequest]
  before_action :received, only: [:index, :show, :friendrequest]
  before_action :all_friends, only: [:index, :show, :friends]
  before_action :friendship, except: [:new, :create, :edit, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def create 
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to signin_path , notice: "#{@user.name} Successfully Signed Up." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'Account Successfully Updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Account was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def friendrequest
    if @received.nil?
      redirect_to users_path
    else
      @users = User.all
    end
  end

  def sentrequest
    if @sent.nil?
      redirect_to users_path
    else
      @users = User.all
    end
  end

  def friends
    if @friends.nil?
      redirect_to users_path
    else
      @users = User.all
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def required_signin
      unless current_user
        flash[:error] = "Please Sign In Properly"
        redirect_to signin_path
      end
    end

    def required_signout
      if current_user
        flash[:error] = "Please Sign out Properly"
        redirect_to users_path
      end
    end

    def sent
      @sent = current_user.sent_request
    end

    def received
      @received = current_user.received_request
    end

    def all_friends
      @friends = current_user.all_friends
    end

    def friendship
      @friendship = Friendship.find_by(user_id: current_user.id, friend_id: params[:id].to_i)|| Friendship.find_by(friend_id: current_user.id, user_id: params[:id].to_i)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # --------------------------------- User is Current User ---------------------------------
  def current_user?(user)
    current_user == user
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Friendbook" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if current_user.present?  %> 
          <a class="navbar-brand" href="/users"> Friendbook </a>
          <a class="navbar-brand" href="#">  </a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">   
            <%= menu_group pull: :right do %>
              <%= menu_item "Sign Out", session_path, method: :delete %>
            <% end %>
            <%= menu_group pull: :right do %>
              <%= menu_item current_user.name, user_path(current_user.id) %>
            <% end %>
          </div>
        <% else %>         
          <a class="navbar-brand" href="/signin"> Friendbook </a>
          <a class="navbar-brand" href="#">  </a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">   
            <%= menu_group pull: :right do %>
              <%= menu_item "Sign Up", signup_path, :class => "btn btn-xs btn-success" %>
            <% end %>
            <%= menu_group pull: :right do %>
              &nbsp
            <% end %>
            <%= menu_group pull: :right do %>
              <%= menu_item "Sign In", signin_path, :class => "btn btn-xs btn-info" %>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <% if current_user.present?  %>
          <div class="col-lg-3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <!-- <li class="nav-header">Sidebar</li> -->
                <li><%= link_to "Friends", friends_path(current_user)  %></li>
                <li><%= link_to "Find Friends", users_path  %></li>
                <li><%= link_to "Friend Request", friendrequest_path(current_user) %></li>
                <li><%= link_to "Sent Request", sentrequest_path(current_user) %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        <% end %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
      <%=f.error_span(:name) %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.email_field :email, :class => 'form-control' %>
      <%=f.error_span(:email) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => 'form-control' %>
      <%=f.error_span(:password) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
      <%=f.error_span(:password_confirmation) %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <% if current_user %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
      <% else %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                signin_path, :class => 'btn btn-default' %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/friendrequest.html.erb
<% if @received.blank? %>
  <h1> Empty </h1>
<% else %>

  <h1> Friend Request </h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% if !current_user?(user) %>
          <tr>    
            <% if @received.include?(user) %>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to t('.show', :default => t("helpers.links.show")),
                        user_path(user), :class => 'btn btn-default btn-xs' %>
                <%= link_to "Accept Request", accept_request_path(user),:method => :post ,:class => "btn btn-default btn-xs" %> 
                <%= link_to "Cancel Request", friendship_path(user),
                        :method => :delete, :class => 'btn btn-default btn-xs' %>
              </td>
            <% end %>
          </tr> 
        <% end %> 
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back', users_path, :class => 'btn btn-default' %>

app/views/users/friends.html.erb
<% if @friends.blank? %>
  <h1> You have no friends </h1>
<% else %>
  <h1> Friend List </h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% if !current_user?(user) %>
          <tr>    
            <% if @friends.include?(user) %>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to "Unfriend", friendship_path(user),
                      :method => :delete, :class => "btn btn-xs btn-danger" %>
              </td>
            <% end %>
          </tr> 
        <% end %> 
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back', users_path, :class => 'btn btn-default' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if !(current_user?(user) || @received.include?(user)) %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        user_path(user), :class => 'btn btn-default btn-xs' %>
            <% if @friends.include?(user)%>
              <%= link_to "Unfriend", friendship_path(user),
                        :method => :delete, :class => "btn btn-xs btn-danger" %>    
            <% elsif @sent.include?(user) %>
              <%= link_to "Cancel Request", friendship_path(user),
                      :method => :delete, :class => "btn btn-xs btn-danger" %>              
            <% else %>
              <%= link_to "Add Friend", create_friendship_path(user),
                        :method => :post, :class => 'btn btn-primary btn-xs' %>
            <% end %>
           </td>
        </tr>
      <% end %> 
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/sentrequest.html.erb
<% if @sent.blank? %>
  <h1> Empty </h1>
<% else %>

  <h1> Sent Friend Request</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% if !current_user?(user) %>
          <tr>    
            <% if @sent.include?(user) %>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= link_to "Cancel Request", friendship_path(user),
                      :method => :delete, :class => "btn btn-xs btn-danger" %>
              </td>
            <% end %>
          </tr>
        <% end %> 
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back', users_path, :class => 'btn btn-default' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<div>
  <%= link_to 'Back', users_path, :class => 'btn btn-default' %>
  <% if current_user?(@user) %>
    <%= link_to 'Edit Profile', edit_user_path(@user), :class => 'btn btn-default' %>
    <%= link_to 'Deactivate Account', user_path(@user),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
  <% end %>
  <%#= link_to 'Cancel', users_path, :class => 'btn btn-default' %>
</div>